version: 2
updates:
  # npm/pnpm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "fco-gt"
    labels:
      - "dependencies"
    groups:
      production-deps:
        dependency-type: "production"
        patterns:
          - "*"
      dev-deps:
        dependency-type: "development"
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
    labels:
      - "ci"
